name: Publicar feature
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".devcontainer/features/0/**"
      - ".github/workflows/publicar.yaml"
jobs:
  publicar:
    runs-on: ubuntu-26.04
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: devcontainers/action@v1.4.4
        with:
          publish-features: "true"
          base-path-to-features: ./.devcontainer/features
          features-namespace: ghcr.io/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}